rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://m.lailer.net/users/66666666
  is_listening: true
- url: https://m.lailer.net/users/5208888
  is_listening: true
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies: {}
lailer:
  sessionid: HdbLlf5p0oyzkYMFAcAgj3FCvsjJ5CFl
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
  custom_commandline: ""
timeout_in_us: 60000000
